# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-02 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='index',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
