# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-25 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_sentences', models.CharField(max_length=250)),
                ('direct_links', models.CharField(max_length=150)),
            ],
        ),
    ]
