# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-04 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_index'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Index',
        ),
        migrations.RemoveField(
            model_name='main',
            name='index',
        ),
    ]
